### PR TITLE
Fix/ update the get support link to correct contact page

### LINKED ISSUE #2433: Update the 'Get Support' Link to Correct Contact Page
### Bug Description

In the WP admin panel under **Dokan > Dashboard** menu displays a **?** in the top right corner, which leads to a **Get Support** option[[Screenshot](https://snipboard.io/U19fgm.jpg)]. The current link for **Get Support** redirects users to https://wedevs.com/account/tickets/?utm_source=plugin&utm_medium=wp-admin&utm_campaign=dokan-lite, which should not be.

### Step To Reproduce

1. Log into WordPress Admin.
2. Navigate to **Dokan > Dashboard**.
3. Click on the '**?**' icon in the top right corner.
4. Select 'Get Support'.
5. Observe that the link redirects to **wedevs.com/account/tickets**

### Expected Behaviour

The 'Get Support' option should direct users to the correct support page at https://dokan.co/contact/ where users can submit a support request.

### Actual Behaviour

As mentioned in the description.

### Additional Information

_No response_

### Environment (please complete the following information)

```shell
1. Dokan Version: 3.13.1
2. Dokan Pro Version: [e.g. v3.1.2]
3. WooCommerce Version: [e.g. v4.9.2]
4. Browser [e.g. chrome, safari]
5. Current Theme: [e.g. Store Front]
```

### PR DESCRIPTION
**Pull request by TanvirHasan19**
### All Submissions:

* [ ] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [ ] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included related pull request(s) (optional)
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Related Pull Request(s)

* Full PR Link

### Closes 

* Closes #2433

### How to test the changes in this Pull Request:

* Steps or issue link

### Changelog entry

```
- **fix:** update the get support link to correct contact page
```

### Before Changes

Describe the issue before changes with screenshots(s).

### After Changes

Describe the issue after changes with screenshot(s).

### Feature Video (optional)

Link of detailed video if this PR is for a feature.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

## Summary by CodeRabbit

- **Documentation**
	- Updated support, getting started, and feature request links in the admin panel to direct users to the latest resources on the official Dokan website.

### CODE REVIEW

File: templates/admin-header.php [hunk 1]
```diff
@@ -109,7 +109,7 @@
                             </div>
                             <?php esc_html_e( 'Community', 'dokan-lite' ); ?>
                         </a>
-                        <a href="https://wedevs.com/docs/dokan/getting-started/?utm_source=plugin&utm_medium=wp-admin&utm_campaign=dokan-lite" target="_blank">
+                        <a href="https://dokan.co/docs/wordpress/getting-started/" target="_blank">
```
Comment (mrabbani) [inline templates/admin-header.php:112]: @getdokan/product-plugin-team,  Should we add `utm`?

Comment (jamil-mahmud) [reply templates/admin-header.php:112]: @mrabbani vai,
Yes kindly do so as previous link was already associated with utm source so in this change we should do similar as that. Kindly proceed vai

Comment (TanvirHasan19) [reply templates/admin-header.php]: @mrabbani bhai, the URL query param is now updated.

File: templates/admin-header.php [hunk 2]
```diff
@@ -134,7 +134,7 @@
                             </div>
                             <?php esc_html_e( 'Basic & Fundamental', 'dokan-lite' ); ?>
                         </a>
-                        <a href="https://wedevs.com/account/dokan-feature-requests/" target="_blank">
+                        <a href="https://dokan.co/wordpress/feature-requests/" target="_blank">
```
Comment (devAsadNur) [inline templates/admin-header.php:137]: @TanvirHasan19 Bhai, please update the feature request link to `https://pluginfeedback.dokan.co/`

Discussion link: https://github.com/getdokan/plugin-internal-tasks/issues/505#issuecomment-2803681792

Comment (TanvirHasan19) [reply templates/admin-header.php]: @devAsadNur bhai, the feature request link has been updated. Thanks!

**Review by devAsadNur — APPROVED** [review]

File: templates/admin-header.php [hunk 3]
```diff
@@ -134,7 +134,7 @@
                             </div>
                             <?php esc_html_e( 'Basic & Fundamental', 'dokan-lite' ); ?>
                         </a>
-                        <a href="https://wedevs.com/account/dokan-feature-requests/" target="_blank">
+                        <a href="https://pluginfeedback.dokan.co/" target="_blank">
```
Comment (mrabbani) [inline templates/admin-header.php:137]: - Pls update the url to `https://pluginfeedback.dokan.co/b/feature-requests`
- Pls also add utm query params.

CC: @getdokan/product-plugin-team

File: templates/admin-header.php [hunk 4]
```diff
@@ -88,7 +88,7 @@
 
                             <?php esc_html_e( 'What’s New', 'dokan-lite' ); ?>
                         </a>
-                        <a href="https://wedevs.com/account/tickets/?utm_source=plugin&utm_medium=wp-admin&utm_campaign=dokan-lite" target="_blank">
+                        <a href="https://dokan.co/contact/" target="_blank">
```
Comment (mrabbani) [inline templates/admin-header.php:91]: Pls also add utm query params.

**Review by mrabbani — CHANGES_REQUESTED** [review]

**Comment by devAsadNur** [comment]
Marged the PR by discussing with @mrabbani Bhai.
