### PR TITLE
Error on approved refund request when empty Commission _dokan_additional_fee #4018

### LINKED ISSUE #2491: Unsupported operand types at `dokan-lite/includes/Commission/Settings/OrderItem.php:74`
### Bug Description

The error log
```
Critical Uncaught TypeError: Unsupported operand types: string / string in /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Commission/Settings/OrderItem.php:74
```
Additional context:
```json
{
"error": {
"type": 1,
"file": "/WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Commission/Settings/OrderItem.php",
"line": 74
},
"remote-logging": true,
"backtrace": [
"",
"#0 /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Commission/Strategies/OrderItem.php(92): WeDevs\\Dokan\\Commission\\Settings\\OrderItem->get()",
"#1 /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Commission/Strategies/AbstractStrategy.php(37): WeDevs\\Dokan\\Commission\\Strategies\\OrderItem->get_settings()",
"#2 /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Commission/Calculator.php(58): WeDevs\\Dokan\\Commission\\Strategies\\AbstractStrategy->create_formula()",
"#3 /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Commission.php(611): WeDevs\\Dokan\\Commission\\Calculator->calculate_commission('180', 1)",
"#4 /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/templates/orders/commission-meta-box-html.php(79): WeDevs\\Dokan\\Commission->get_commission(Array)",
"#5 /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/functions.php(836): include('/home/customer/...')",
"#6 /WEBSITE_ROOT/public_html/wp-content/plugins/dokan-lite/includes/Order/Admin/Hooks.php(604): dokan_get_template_part('orders/commissi...', '', Array)",
"#7 /WEBSITE_ROOT/public_html/wp-admin/includes/template.php(1456): WeDevs\\Dokan\\Order\\Admin\\Hooks->commission_meta_box(Object(WP_Post), Array)",
"#8 /WEBSITE_ROOT/public_html/wp-admin/edit-form-advanced.php(722): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))",
"#9 /WEBSITE_ROOT/public_html/wp-admin/post.php(206): require('/home/customer/...')",
"#10 {main}",
"thrown"
]
}
```

### Step To Reproduce

Go to refund requests by vendors and try to approve it

### Expected Behaviour

Everything works fine

### Actual Behaviour

Critical Uncaught TypeError: Unsupported operand types: `string / string`

### Additional Information

The patch we've done that worked
```diff
diff --git a/includes/Commission/Settings/OrderItem.php b/includes/Commission/Settings/OrderItem.php
index e3ee631c..c239927f 100644
--- a/includes/Commission/Settings/OrderItem.php
+++ b/includes/Commission/Settings/OrderItem.php
@@ -64,9 +64,9 @@ class OrderItem implements InterfaceSetting {
if ( $order_id && OrderUtil::is_hpos_enabled() ) {
$order = dokan()->order->get( $order_id );
- $item_total = $order->get_meta( '_dokan_item_total' );
+ $item_total = (float) $order->get_meta( '_dokan_item_total' );
} else {
- $item_total = get_post_meta( $order_id, '_dokan_item_total', true );
+ $item_total = (float) get_post_meta( $order_id, '_dokan_item_total', true );
}

$product_price = (float) wc_format_decimal( $this->product_price_to_calculate_commission );
if ( $order_id && $item_total ) {
-  $additional_flat = ( $additional_flat / $item_total ) * $product_price;
+  $additional_flat = ( ((float) $additional_flat) / $item_total ) * $product_price;
}
```

### Environment (please complete the following information)

```shell
1. Dokan Version: v3.14.3
2. Dokan Pro Version: v3.14.1
3. WooCommerce Version: v9.5.1
4. Browser: Chrome (Chromium Engine Version 131.0.6778.140)
5. Current Theme: Storefront
6. WordPress version 6.7.1
7. PHP version 8.2.26
```

### PR DESCRIPTION
**Pull request by osmansufy**
### All Submissions:

* [ ] My code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)
* [ ] My code satisfies feature requirements
* [ ] My code is tested
* [ ] My code passes the PHPCS tests
* [ ] My code has proper inline documentation
* [ ] I've included related pull request(s) (optional)
* [ ] I've included developer documentation (optional)
* [ ] I've added proper labels to this pull request

### Related Pull Request(s)

* Full PR Link

### Closes 

* Closes https://github.com/getdokan/dokan-pro/issues/4018
* Closes https://github.com/getdokan/dokan-pro/issues/4021
* Closes #2491

### How to test the changes in this Pull Request:

* Steps or issue link

- Do a refund request specially from admin end 
- try to approved
- Check in both case (HPOS enable / disable)

### Changelog entry
```md
bug fixed for empty admin commission additional fee
```

*Title*

Detailed Description of the pull request. What was previous behaviour
and what will be changed in this PR.

### Before Changes

Describe the issue before changes with screenshots(s).

### After Changes

Describe the issue after changes with screenshot(s).

### Feature Video (optional)

Link of detailed video if this PR is for a feature.

### PR Self Review Checklist:

* Code is not following code style guidelines
* Bad naming: make sure you would understand your code if you read it a few months from now.
* KISS: Keep it simple, Sweetie (not stupid!).
* DRY: Don't Repeat Yourself.
* Code that is not readable: too many nested 'if's are a bad sign.
* Performance issues
* Complicated constructions that need refactoring or comments: code should almost always be self-explanatory.
* Grammar errors.

### FOR PR REVIEWER ONLY:

> As a reviewer, your feedback should be focused on the idea, not the person. Seek to understand, be respectful, and focus on constructive dialog.

> As a contributor, your responsibility is to learn from suggestions and iterate your pull request should it be needed based on feedback. Seek to collaborate and produce the best possible contribution to the greater whole.

* [ ] Correct — Does the change do what it’s supposed to? ie: code 100% fulfilling the requirements?
* [ ] Secure — Would a nefarious party find some way to exploit this change? ie: everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities?
* [ ] Readable — Will your future self be able to understand this change months down the road?
* [ ] Elegant — Does the change fit aesthetically within the overall style and architecture?

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved safety of calculations to prevent potential division by zero errors in order item settings. 
	- Enhanced retrieval of item totals to ensure consistent data handling.

### CODE REVIEW

File: includes/Commission/Settings/OrderItem.php [hunk 1]
```diff
@@ -71,7 +71,8 @@ public function get(): Setting {
 
         $product_price = (float) wc_format_decimal( $this->product_price_to_calculate_commission );
         if ( $order_id && $item_total ) {
-            $additional_flat = ( $additional_flat / $item_total ) * $product_price;
+            $empty_safe_additional_flat = empty( $additional_flat ) ? 0 : $additional_flat;
```
Comment (mrabbani) [inline includes/Commission/Settings/OrderItem.php:74]: Could you re-write as:

```php
 $additional_flat = ( floatval( $additional_flat ) / $item_total ) * $product_price;
```

**Review by mrabbani — CHANGES_REQUESTED** [review]

**Review by mrabbani — APPROVED** [review]

**Review by Aunshon — APPROVED** [review]
